import os
import datetime
import markdown
from xhtml2pdf import pisa


def build_markdown_content(response_text: str) -> str:
    """Build the formatted markdown content with metadata header."""
    return f"""# 🌍 AI Travel Plan

**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}
**Created by:** Jarvis

---

{response_text}

---

*This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
"""


def save_document(response_text: str, directory: str = "./output") -> str | None:
    """Export travel plan to Markdown file."""
    os.makedirs(directory, exist_ok=True)
    markdown_content = build_markdown_content(response_text)

    try:
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"{directory}/AI_Trip_Planner_{timestamp}.md"

        with open(filename, "w", encoding="utf-8") as f:
            f.write(markdown_content)

        print(f"Markdown file saved as: {filename}")
        return filename

    except Exception as e:
        print(f"Error saving markdown file: {e}")
        return None


def save_document_as_pdf(response_text: str, directory: str = "./output") -> str | None:
    """Export travel plan to a PDF file."""
    os.makedirs(directory, exist_ok=True)
    markdown_content = build_markdown_content(response_text)

    # Convert markdown -> HTML
    html_body = markdown.markdown(markdown_content, extensions=["extra"])

    # Wrap with minimal styling so the PDF doesn't look bare
    html_content = f"""
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{ font-family: Helvetica, Arial, sans-serif; font-size: 12px; line-height: 1.5; color: #1C2321; }}
            h1 {{ font-size: 22px; color: #C1622D; }}
            h2 {{ font-size: 17px; color: #2A6F77; margin-top: 20px; }}
            hr {{ border: none; border-top: 1px solid #ccc; margin: 16px 0; }}
            em {{ color: #555; font-size: 10px; }}
        </style>
    </head>
    <body>{html_body}</body>
    </html>
    """

    try:
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"{directory}/AI_Trip_Planner_{timestamp}.pdf"

        with open(filename, "wb") as f:
            pisa_status = pisa.CreatePDF(html_content, dest=f)

        if pisa_status.err:
            print(f"Error generating PDF: {pisa_status.err}")
            return None

        print(f"PDF file saved as: {filename}")
        return filename

    except Exception as e:
        print(f"Error saving PDF file: {e}")
        return None